"""add workout_log

Revision ID: 5456c571037d
Revises: 995bec0c6fd8
Create Date: 2026-05-29 18:44:42.146974
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5456c571037d"
down_revision: str | None = "995bec0c6fd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("template_slug", sa.String(length=96), nullable=False),
        sa.Column("name_tr", sa.String(length=160), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=True),
        sa.Column("reps", sa.String(length=32), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("kcal", sa.Integer(), nullable=True),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workout_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workout_log_day"), ["day"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workout_log_day"))

    op.drop_table("workout_log")
    # ### end Alembic commands ###
