"""add photo_path to meal_log

Revision ID: 995bec0c6fd8
Revises: 21d2cb59f802
Create Date: 2026-05-28 13:59:15.936280
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "995bec0c6fd8"
down_revision: str | None = "21d2cb59f802"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meal_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("photo_path", sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meal_log", schema=None) as batch_op:
        batch_op.drop_column("photo_path")

    # ### end Alembic commands ###
